// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#ifndef THINGSPROPERTIES_H
#define THINGSPROPERTIES_H


#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = "f4bad2e4-8997-4e70-8455-79319160c7c3";
const char DEVICE_LOGIN_NAME[]  = "494cd2da-6a4f-4022-acc5-c1bf9eb957c5";

const char SSID[]               = "Amegakure";    // Network SSID (name)
const char PASS[]               = "1235abce";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "F8OF7FX1YRDOHA5DYUPB";    // Secret device password


void onStControlCodeChange();

float tempAtual;
String stControlCode;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(tempAtual, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(stControlCode, READWRITE, ON_CHANGE, onStControlCodeChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);


#endif